FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    ghostscript \
    && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /data

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD gunicorn -w 2 --timeout 300 -k uvicorn.workers.UvicornWorker app.main:app --bind 0.0.0.0:$PORT